export const DataVideoYoutube = [
    {
      id: 1,
      name: 'Video lỗi',
      description: null,
      url: 'https://www.youtube.com/watch?v=U_dvo7W3TZ8',
      toNumberUser: 17,
      numberView: 0,
      numberViewUnique: 0,
      numberNotMemberUnique: 3,
      numberMemberUnique: 0,
      appId: 1,
      createdTime: '2020/06/22 13:53',
      updatedTime: '2020/06/22 13:53',
      updatedBy: 1,
      updatedByName: null,
      deleted: false,
      openWithWebview: false,
      videoHasCoupon: true,
    },
    {
      id: 2,
      name:
        'Nhạc Chill 2020 - Nhạc Này Chill Phết - Những Bản Lofi Việt Nhẹ Nhàng Cực Chill (P3)',
      description: null,
      url: 'https://www.youtube.com/watch?v=gQ3cEEPIu9c',
      toNumberUser: 17,
      numberView: 0,
      numberViewUnique: 0,
      numberNotMemberUnique: 2,
      numberMemberUnique: 1,
      appId: 1,
      createdTime: '2020/06/19 18:44',
      updatedTime: '2020/06/19 18:44',
      updatedBy: 1,
      updatedByName: null,
      deleted: false,
      openWithWebview: false,
      videoHasCoupon: false,
    },
    {
      id: 3,
      name: 'Nhạc Chill Tiktok - Em Ơi Đừng Sầu..Em Ơi Đừng Buồn, Ví Dầu Đưa Dâu Lofi, Nhạc Lofi Hot Nhất TikTok',
      description: null,
      url: 'https://www.youtube.com/watch?v=BGYIn3tPbQQ',
      toNumberUser: 17,
      numberView: 0,
      numberViewUnique: 0,
      numberNotMemberUnique: 0,
      numberMemberUnique: 0,
      appId: 1,
      createdTime: '2020/06/19 17:59',
      updatedTime: '2020/06/19 17:59',
      updatedBy: 1,
      updatedByName: null,
      deleted: false,
      openWithWebview: false,
      videoHasCoupon: true,
    },
    {
      id: 4,
      name:
        'Một Nhành Mai (Nhất Tiễn Mai Remix) 一剪梅 Trác Y Đình Remix | Nhạc Tik Tok Gây Nghiện',
      description: null,
      url: 'https://www.youtube.com/watch?v=GcCJ6FGWsBw',
      toNumberUser: 15,
      numberView: 0,
      numberViewUnique: 0,
      numberNotMemberUnique: 2,
      numberMemberUnique: 0,
      appId: 1,
      createdTime: '2020/06/19 02:08',
      updatedTime: '2020/06/19 02:08',
      updatedBy: 1,
      updatedByName: null,
      deleted: false,
      openWithWebview: false,
      videoHasCoupon: false,
    },
  ];
  