module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  env: {
    production: {
      plugins: ['transform-remove-console'],
    },
  },
  plugins: [
    '@babel/plugin-transform-runtime',
    ['module-resolver', {
      root: ['.'],
      alias: { 
        '@assets': './assets',
        '@analytics': './analytics',
        "@api":'./src/api',
        "@const":'./src/const',
        "@css":'./src/css',
        "@context":'./src/context',
        "@element":'./src/element',
        "@fireBase":'./src/fireBase',
        "@HOC":'./src/HOC',
        "@hooks":'./src/hooks',
        "@images":'./src/images',
        "@language":'./src/language',
        "@libJS":'./src/libJS',
        "@nativeModule":'./src/nativeModule',
        "@navigation":'./src/navigation',
        "@redux":'./src/redux',
        "@resources":'./src/resources',
        "@screen":'./src/screen',
        "@security":'./src/security',
        "@sentry":'./src/sentry',
        "@server":'./src/server',
        "@services":'./src/services',
        "@sql":'./src/sql',
        "@socket":'./src/socket',
        "@util":'./src/util',
      },
    }],
  ],
  exclude: ['**/*.png', '**/*.jpg', '**/*.gif'],
};