export default ColorConvert = {
    colorsLinearGradient: ["white", "white", "white"],
    colorMain: "#00C6AD",
    colorCancel: "#FF6F5B",
    colorBtBack: "#D4FAFF",
    colorBtEdit: "#FFE2DE",
    colorBg2: "#E7E5FF",
    colorIcon: "#2AD3E7",
    colorText: "#1A1A1A",
    textLabel: "#747F9E",
    btClosedPopup: "#345",
    colorText1: "#5C6979",
    colorTitleScreen: "#000000",
    colorTextMenu: "#262C3D",
    colorTextDes: "#95989A",
    colorBorder: "#B0B3C7",
    todayColorCalendar: "#FFAA00",
    registrationDateCalendar: "#00C6AD",
    dayOffCalendar: "#FF0000",
    disabledDateCalendar: "#E4E4E4",
    colorButtonDisable: "#C1C1C1",
    backgroundSearch: "#F8F8F8",
    placeholderTextColor: "#C5C5C5",
    bgStatus1: "#FFF9E8",
    textStatus1: "#FFC107",
    bgStatus3: "#C3C3C3",
    colorSecondary: "#DBFFFA",
    colorDefault: "#707070",
    colorTabMenuBarInActive: "#6E6E6E"
};
