
const keyNavigation = {
  APP_INTRO: "APP_INTRO",
  REGISTER: "REGISTER",
  HOME: "HOME",
  LOGIN: "LOGIN",
  POLICY: "POLICY",
  BOTTOM_TAB: "BOTTOMTAB",
  BASIC_JS: "BASIC_JS",
  BASIC_TS: "BASIC_TS",
  PUSH_NOTIFICATIONS: "PUSH_NOTIFICATIONS",
  ACCOUNT: "ACCOUNT",
  DISCOVERY: "DISCOVERY",
  INFO_DEVICES_AND_APP: `Thông tin ứng dụng`,
  NEWS: "NEWS",
  WEATHER: "WEATHER",
  ANIMATIONS: "ANIMATIONS",
  MAP: "MAP",
  CAMERA: "CAMERA",
  BASIC: "BASIC",
  BASIC_MENU_SCREEN: "BASIC_MENU_SCREEN",
  FILE: "FILE",
  NATIVE_MODULE_ANDROID: "NATIVE_MODULE_ANDROID",
  SOUND: "SOUND",
  WEBVIEW: "WEBVIEW",
  VIDEO: "VIDEO",
  SOCKET: "SOCKET",
  SYSTEM_LOG: "SYSTEM_LOG",
  SERVER_NODEJS: 'SERVER_NODEJS',
  CHART :"CHART",
  FIRE_BASE: "FIRE_BASE",
  SECURITY: "SECURITY",
  MINI_APP: "MINI_APP",
  FREQUENTLY_QUESTIONS:"FREQUENTLY_QUESTIONS",
  PDA:"PDA",

  //Menu khám phá:
  DISCOVERY_FIREBASE_AUTHEN: "DISCOVERY_FIREBASE_AUTHEN",
  DISCOVERY_MAP: "DISCOVERY_MAP",
  DISCOVERY_CALENDAR: "DISCOVERY_CALENDAR",
  DISCOVERY_CAMERA: "DISCOVERY_CAMERA",
  DISCOVERY_CHAT: "DISCOVERY_CHAT",

  //Root stack:
  ROOT_STACK_BOTTOM: "ROOT_STACK_BOTTOM",
  ROOT_STACK_DRAWER: "ROOT_STACK_DRAWER"
};

export { keyNavigation };

